#!/bin/bash

rm -rvf *-50k.json
mkdir -p build

# important: check the file structure of the zip file to addapt to you
if [ ! -f build/nxparroquias.shp ]; then
  curl -ko build/ecuador.zip 'https://www.ecuadorencifras.gob.ec//documentos/web-inec/Cartografia/Clasificador_Geografico/2012/SHP.zip'
  unzip -od build build/ecuador.zip SHP/nxparroquias.shp SHP/nxparroquias.dbf 
  for i in build/SHP/nxparroquias.*; do mv -- "$i" "${i/SHP\/nxparroquias/ecuador}"; done
  rmdir build/SHP
  chmod a-x build/ecuador.*
fi

shp2json -n --encoding UTF-8 build/ecuador.shp \
  | ndjson-map 'd.properties' \
  | json2csv -n > build/dictionary.csv
dictionary="$(iconv -f ISO8859-1 -t UTF-8 build/dictionary.csv | awk -F "\"*,\"*" -v OFS=',' '{print $1, $2, $5, $6, $7, $8}' | awk '{gsub(/"/,"")};1')"
echo "$dictionary" > build/dictionary.csv

# the shp file is already projected with the best version of ecuador
# so do not reproject again and rename the file to express that is already projected 
geo2topo -q 1e5 -n level4=<( \
  mapshaper build/ecuador.shp -simplify 3% keep-shapes -clean -o \ format=geojson - \
    | ndjson-cat \
    | ndjson-split 'd.features' \
    | ndjson-map '(d.id = d.properties.DPA_PARROQ, delete d.properties, d)') \
  | topomerge level3=level4 -k 'd.id.slice(0, 4)'\
  | topomerge level2=level3 -k 'd.id.slice(0, 2)'\
  | topomerge level1=level2 \
  | node ./properties.js \
  > ecuador-transverse_mercator-50k.json
  

